version: "3.4"

services:
  mysql-db:
    container_name: mysql-db-test-container
    image: mysql:${MYSQL_VERSION}
    command: --sql_mode="" --default-authentication-plugin=mysql_native_password --wait-timeout=1830
    volumes:
      - ./mysql-db-data:/var/lib/mysql
      - ./resources:/resources
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
